### ISSUE TITLE
Not appearing in ModSettings

### ISSUE THREAD

**Issue by hozz1235** [zeobviouslyfakeacc/CacheControl#1]
Hello.  I've followed directions for installation and this is not appearing in ModSettings (other mods are).  Help?  Thank you.

**Comment by zeobviouslyfakeacc** [comment]
It's not supposed to show up in the mod settings menu - it shows up in the menu that you use to create a custom mode survival game. It should be at the bottom of the "Gear" category. There are [instructions here on GitHub](https://github.com/zeobviouslyfakeacc/CacheControl#instructions).

If it also doesn't show up in the custom mode menu: Please upload both your MelonLoader log file and your TLD log file here. You can attach files by dragging and dropping them in this window.
- The MelonLoader log file is in your game directory at `...\TheLongDark\Logs`
- The TLD log file "output_log.txt" is at `%AppData%\..\LocalLow\Hinterland\TheLongDark`

**Comment by hozz1235** [comment]
You're right, I apologize.  Thank  you very much for your time and effort on TLD mods.

**Comment by zeobviouslyfakeacc** [comment]
There's nothing to apologize for. That's kinda on me: neutral technical sentences get viewed as slightly negative & pissed off, even though they're (usually) not intended that way. That's why I tend to go a bit overboard with emoji sometimes 😅 

Enjoy the mods! 😄

**Comment by hozz1235** [comment]
No, I get it!  You left immaculate instructions and I failed to find/read them!  I'm a dev as well so I understand where you're coming from!  Keep up the mods!  Wish I could do what you do.
